package com.ms.greendaolibrary.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "COLLECT_ENTITY".
 */
public class CollectEntity {

    private Long id;
    private String html_id;
    private String collect;

    public CollectEntity() {
    }

    public CollectEntity(Long id) {
        this.id = id;
    }

    public CollectEntity(Long id, String html_id, String collect) {
        this.id = id;
        this.html_id = html_id;
        this.collect = collect;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getHtml_id() {
        return html_id;
    }

    public void setHtml_id(String html_id) {
        this.html_id = html_id;
    }

    public String getCollect() {
        return collect;
    }

    public void setCollect(String collect) {
        this.collect = collect;
    }

}
