package com.ms.greendaolibrary.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.ms.greendaolibrary.db.HtmlEntity;

import com.ms.greendaolibrary.db.HtmlEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig htmlEntityDaoConfig;

    private final HtmlEntityDao htmlEntityDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        htmlEntityDaoConfig = daoConfigMap.get(HtmlEntityDao.class).clone();
        htmlEntityDaoConfig.initIdentityScope(type);

        htmlEntityDao = new HtmlEntityDao(htmlEntityDaoConfig, this);

        registerDao(HtmlEntity.class, htmlEntityDao);
    }
    
    public void clear() {
        htmlEntityDaoConfig.getIdentityScope().clear();
    }

    public HtmlEntityDao getHtmlEntityDao() {
        return htmlEntityDao;
    }

}
