package com.ms.greendaolibrary.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "HTML_ENTITY".
 */
public class HtmlEntity {

    private Long id;
    private String url;
    private String type;
    private String title;
    private String html;
    private String summary;
    private String collect;
    private java.util.Date hireDate;

    public HtmlEntity() {
    }

    public HtmlEntity(Long id) {
        this.id = id;
    }

    public HtmlEntity(Long id, String url, String type, String title, String html, String summary, String collect, java.util.Date hireDate) {
        this.id = id;
        this.url = url;
        this.type = type;
        this.title = title;
        this.html = html;
        this.summary = summary;
        this.collect = collect;
        this.hireDate = hireDate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getHtml() {
        return html;
    }

    public void setHtml(String html) {
        this.html = html;
    }

    public String getSummary() {
        return summary;
    }

    public void setSummary(String summary) {
        this.summary = summary;
    }

    public String getCollect() {
        return collect;
    }

    public void setCollect(String collect) {
        this.collect = collect;
    }

    public java.util.Date getHireDate() {
        return hireDate;
    }

    public void setHireDate(java.util.Date hireDate) {
        this.hireDate = hireDate;
    }

}
